# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'FWPopupView' do
  
  # 布局：https://github.com/SnapKit/SnapKit
  pod 'SnapKit', '~> 5.0.1'

  # IQKeyboardManagerSwift：https://github.com/hackiftekhar/IQKeyboardManager
  pod 'IQKeyboardManagerSwift'

end
